//
//  Word.swift
//  Taboo-Game
//
//  Created by Hüseyin GÜLECEN on 19.01.2021.
//

import Foundation

var wordsArray : [Word] = []

class Word{
    
    var wordDescribe: String
    var wordForbidden1: String
    var wordForbidden2: String
    var wordForbidden3: String
    var wordForbidden4: String
    var wordForbidden5: String

    

    init(wordDescribe: String,wordForbidden1: String,wordForbidden2: String,wordForbidden3: String,wordForbidden4: String,wordForbidden5: String ) {
    
        self.wordDescribe = wordDescribe
        
        self.wordForbidden1 = wordForbidden1
        
        self.wordForbidden2 = wordForbidden2
        
        self.wordForbidden3 = wordForbidden3
        
        self.wordForbidden4 = wordForbidden4
        self.wordForbidden5 = wordForbidden5
        
    }
   
}

func wordLists ()
{
    wordsArray.append(Word(wordDescribe: "FİİL", wordForbidden1: "İŞ", wordForbidden2: "OLUŞ", wordForbidden3: "HAREKET", wordForbidden4: "EYLEM", wordForbidden5: "SÖZCÜK"))
    
    wordsArray.append(Word(wordDescribe: "UYAK", wordForbidden1: "ŞİİR", wordForbidden2: "DİZE", wordForbidden3: "BENZERLİK", wordForbidden4: "KAFİYE", wordForbidden5: "SES"))
    wordsArray.append(Word(wordDescribe: "SÖZLÜK", wordForbidden1: "ANLAM", wordForbidden2: "KELİME", wordForbidden3: "SÖZCÜK", wordForbidden4: "AÇIKLAMA", wordForbidden5: "LÜGAT"))
    wordsArray.append(Word(wordDescribe: "KUŞBAKIŞI ", wordForbidden1: "HARİTA", wordForbidden2: "TEPE", wordForbidden3: "YUKARI", wordForbidden4: "GÖRMEK", wordForbidden5: "KROKİ"))
    wordsArray.append(Word(wordDescribe: "OKKA", wordForbidden1: "AĞIRLIK", wordForbidden2: "ÖLÇÜ", wordForbidden3: "BİRİM", wordForbidden4: "KİLO", wordForbidden5: "TARTI"))
    wordsArray.append(Word(wordDescribe: "KÖK", wordForbidden1: "SÖZCÜK", wordForbidden2: "YAPIM", wordForbidden3: "ÇEKİM", wordForbidden4: "EK", wordForbidden5: "KELİME"))
    wordsArray.append(Word(wordDescribe: "ŞİİR", wordForbidden1: "ŞAİR", wordForbidden2: "MISRA", wordForbidden3: "DİZE", wordForbidden4: "KITA", wordForbidden5: "DÖRTLÜK"))
    wordsArray.append(Word(wordDescribe: "ÖYKÜ", wordForbidden1: "HİKÂYE", wordForbidden2: "KAHRAMAN", wordForbidden3: "YAZAR", wordForbidden4: "YER", wordForbidden5: "KİTAP"))
    wordsArray.append(Word(wordDescribe: "MASAL", wordForbidden1: "OLAĞANÜSTÜ", wordForbidden2: "KAHRAMAN", wordForbidden3: "YAZAR", wordForbidden4: "KELOĞLAN", wordForbidden5: "KİTAP"))
    wordsArray.append(Word(wordDescribe: "FAY", wordForbidden1: "HAT", wordForbidden2: "DEPREM", wordForbidden3: "KIRILMAK", wordForbidden4: "SARSILMAK", wordForbidden5: "İSTANBUL"))
    wordsArray.append(Word(wordDescribe: "KÜÇÜMSEME", wordForbidden1: "NİTELİK", wordForbidden2: "DEĞERSİZ", wordForbidden3: "YARGI", wordForbidden4: "CÜMLE", wordForbidden5: "AZIMSAMA"))
    wordsArray.append(Word(wordDescribe: "METRES", wordForbidden1: "KARI KOCA", wordForbidden2: "EVLİ", wordForbidden3: "ALDATMAK", wordForbidden4: "YASAK", wordForbidden5: "İLİŞKİ"))
    wordsArray.append(Word(wordDescribe: "FAX", wordForbidden1: "ÇEKMEK", wordForbidden2: "GÖNDERMEK", wordForbidden3: "YAZI", wordForbidden4: "KAĞIT", wordForbidden5: "FOTOKOPİ"))
    wordsArray.append(Word(wordDescribe: "GAZİ", wordForbidden1: "SAVAŞ", wordForbidden2: "YARALANMAK", wordForbidden3: "ŞEHİT", wordForbidden4: "İSTİKLAL MADALYASI", wordForbidden5: "ATATÜRK"))
    wordsArray.append(Word(wordDescribe: "VEKTÖR", wordForbidden1: "YÖN", wordForbidden2: "FİZİK", wordForbidden3: "SKALER", wordForbidden4: "ÇİZMEK", wordForbidden5: "DOĞRU"))
    wordsArray.append(Word(wordDescribe: "HASIRALTI ETMEK", wordForbidden1: "SAKLAMAK", wordForbidden2: "GİZLEMEK", wordForbidden3: "KORUMAK", wordForbidden4: "YOK ETMEK", wordForbidden5: "ÖRTBAS"))
    wordsArray.append(Word(wordDescribe: "VENEDİK", wordForbidden1: "GONDOL", wordForbidden2: "ÜLKE", wordForbidden3: "SU", wordForbidden4: "İTALYA", wordForbidden5: "YÜZMEK"))
    wordsArray.append(Word(wordDescribe: "SELÜLİT", wordForbidden1: "BACAK", wordForbidden2: "KADIN", wordForbidden3: "CİLT", wordForbidden4: "YAĞ", wordForbidden5: "PORTAKAL"))
    wordsArray.append(Word(wordDescribe: "NORM", wordForbidden1: "KURAL", wordForbidden2: "YERLEŞMİŞ", wordForbidden3: "İLKE", wordForbidden4: "YASA", wordForbidden5: "DÜZEN"))
    wordsArray.append(Word(wordDescribe: "ALT", wordForbidden1: "ÜST", wordForbidden2: "YER", wordForbidden3: "TABAN", wordForbidden4: "DERECE", wordForbidden5: "SINIF"))
    wordsArray.append(Word(wordDescribe: "ABONE", wordForbidden1: "YONCA EVCİMİK", wordForbidden2: "SATIN ALMAK", wordForbidden3: "ÜYE", wordForbidden4: "DERGİ", wordForbidden5: "GAZETE"))
    wordsArray.append(Word(wordDescribe: "TEZGAH", wordForbidden1: "KURMAK", wordForbidden2: "MASA", wordForbidden3: "MUTFAK", wordForbidden4: "SATICI", wordForbidden5: "BÜFE"))
    wordsArray.append(Word(wordDescribe: "TEMAS", wordForbidden1: "FİZİKSEL", wordForbidden2: "DEĞME", wordForbidden3: "DOKUNMA", wordForbidden4: "MÜNASEBET", wordForbidden5: "BULUŞMAK"))
    wordsArray.append(Word(wordDescribe: "EFSANE", wordForbidden1: "HAYALİ", wordForbidden2: "YARADILIŞ", wordForbidden3: "ÖYKÜ", wordForbidden4: "ABARTMAK", wordForbidden5: "SÖYLENCE"))
    wordsArray.append(Word(wordDescribe: "İMLA", wordForbidden1: "KURAL", wordForbidden2: "YAZIM", wordForbidden3: "DİL BİLGİSİ", wordForbidden4: "HATA", wordForbidden5: "TERİM"))
    wordsArray.append(Word(wordDescribe: "SAKAL", wordForbidden1: "KIL", wordForbidden2: "YÜZ", wordForbidden3: "TIRAŞ", wordForbidden4: "KESMEK", wordForbidden5: "TOP"))
    wordsArray.append(Word(wordDescribe: "LOSYON", wordForbidden1: "TIRAŞ", wordForbidden2: "KOLONYA", wordForbidden3: "PARFÜM", wordForbidden4: "KOKU", wordForbidden5: "BERBER"))
    wordsArray.append(Word(wordDescribe: "BARBAR", wordForbidden1: "KABA", wordForbidden2: "İLKEL", wordForbidden3: "KIRICI", wordForbidden4: "UYGARLAŞMA", wordForbidden5: "AKIN"))
    wordsArray.append(Word(wordDescribe: "FABL", wordForbidden1: "MASAL", wordForbidden2: "HAYVAN", wordForbidden3: "HİKAYE", wordForbidden4: "ÖYKÜ", wordForbidden5: "DERS"))
    wordsArray.append(Word(wordDescribe: "ABDESTHANE", wordForbidden1: "TUVALET", wordForbidden2: "WC", wordForbidden3: "HELA", wordForbidden4: "YÜZNUMARA", wordForbidden5: "ALMAK"))
    wordsArray.append(Word(wordDescribe: "HAKİ", wordForbidden1: "RENK", wordForbidden2: "YEŞİL", wordForbidden3: "KAHVERENGİ", wordForbidden4: "ÇALMAK", wordForbidden5: "KAÇMAK"))
    wordsArray.append(Word(wordDescribe: "LATİN AMERİKA", wordForbidden1: "GÜNEY", wordForbidden2: "KITA", wordForbidden3: "BREZİLYA", wordForbidden4: "ÜLKE", wordForbidden5: "ARJANTİN"))
    wordsArray.append(Word(wordDescribe: "DEFİNE", wordForbidden1: "HARİTA", wordForbidden2: "PARA", wordForbidden3: "ALTIN", wordForbidden4: "ALİ", wordForbidden5: "BABA"))
    wordsArray.append(Word(wordDescribe: "ARAMAK", wordForbidden1: "SAÇ", wordForbidden2: "ARAŞTIRMAK", wordForbidden3: "DERLEMEK", wordForbidden4: "ATEŞLEMEK", wordForbidden5: "AYIKLAMAK"))
    wordsArray.append(Word(wordDescribe: "İPUCU", wordForbidden1: "İZ", wordForbidden2: "EMARE", wordForbidden3: "VERMEK", wordForbidden4: "DEDEKTİF", wordForbidden5: "SIR"))
    wordsArray.append(Word(wordDescribe: "ALTIN", wordForbidden1: "TAKMAK", wordForbidden2: "DEĞERLİ", wordForbidden3: "KUYUMCU", wordForbidden4: "SARRAF", wordForbidden5: "ÇEYREK"))
    wordsArray.append(Word(wordDescribe: "AÇISAL HIZ", wordForbidden1: "FİZİK", wordForbidden2: "VEKTÖREL", wordForbidden3: "HAREKET", wordForbidden4: "DAİRESEL", wordForbidden5: "TARAMAK"))
    wordsArray.append(Word(wordDescribe: "SÜZMEK", wordForbidden1: "SU", wordForbidden2: "AYIRMAK", wordForbidden3: "SIVI", wordForbidden4: "MAKARNA", wordForbidden5: "KATI"))
    wordsArray.append(Word(wordDescribe: "KABAKULAK", wordForbidden1: "HASTALIK", wordForbidden2: "İLTİHAP", wordForbidden3: "ŞİŞMEK", wordForbidden4: "BEZ", wordForbidden5: "TÜKÜRÜK"))
    wordsArray.append(Word(wordDescribe: "KÜF", wordForbidden1: "EKMEK", wordForbidden2: "YEŞİL", wordForbidden3: "MANTAR", wordForbidden4: "BAKTERİ", wordForbidden5: "KURT"))
    wordsArray.append(Word(wordDescribe: "ANATOMİ", wordForbidden1: "VÜCUT", wordForbidden2: "SİSTEM", wordForbidden3: "İNCELEMEK", wordForbidden4: "ORGAN", wordForbidden5: "DİŞ"))
    wordsArray.append(Word(wordDescribe: "KARL MARX", wordForbidden1: "SOSYALİZM", wordForbidden2: "KOMÜNİZM", wordForbidden3: "FELSEFE", wordForbidden4: "MANİFESTO", wordForbidden5: "KAPİTAL"))
    wordsArray.append(Word(wordDescribe: "ALTERNATİF AKIM", wordForbidden1: "DOĞRU", wordForbidden2: "ELEKTRİK", wordForbidden3: "DEĞİŞKEN", wordForbidden4: "NİKOLA TESLA", wordForbidden5: "SİNÜS"))
    wordsArray.append(Word(wordDescribe: "FOTOKOPİ", wordForbidden1: "KOPYA", wordForbidden2: "MAKİNE", wordForbidden3: "FAX", wordForbidden4: "TARAMAK", wordForbidden5: "KIRTASİYE"))
    wordsArray.append(Word(wordDescribe: "BARKOD", wordForbidden1: "ÜRÜN", wordForbidden2: "FİYAT", wordForbidden3: "İMZA", wordForbidden4: "ÇİZGİ", wordForbidden5: "ALT"))
    wordsArray.append(Word(wordDescribe: "ODAK", wordForbidden1: "OPTİK", wordForbidden2: "IŞIK", wordForbidden3: "KAYNAK", wordForbidden4: "TOPLANMAK", wordForbidden5: "MİHRAK"))
    wordsArray.append(Word(wordDescribe: "MAKAS", wordForbidden1: "KUMAŞ", wordForbidden2: "KESMEK", wordForbidden3: "KAĞIT", wordForbidden4: "NİŞAN", wordForbidden5: "TERZİ"))
    wordsArray.append(Word(wordDescribe: "KANTİN", wordForbidden1: "OKUL", wordForbidden2: "TOST", wordForbidden3: "KAFETERYA ", wordForbidden4: "ÖĞRENCİ ", wordForbidden5: "YEMEK"))
    wordsArray.append(Word(wordDescribe: "İMA ETMEK", wordForbidden1: "ANLAM ", wordForbidden2: "İZ ", wordForbidden3: "DURUM ", wordForbidden4: "DAVRANIŞ ", wordForbidden5: "ALAMET"))
    wordsArray.append(Word(wordDescribe: "MÜHİMMAT", wordForbidden1: "DEPO ", wordForbidden2: "SAVAŞ ", wordForbidden3: "CEPHANE ", wordForbidden4: "ORDU ", wordForbidden5: "SİLAH"))
    wordsArray.append(Word(wordDescribe: "HIÇKIRIK", wordForbidden1: "SES ", wordForbidden2: "TUTMAK ", wordForbidden3: "DİYAFRAM ", wordForbidden4: "SU ", wordForbidden5: "NEFES"))
    wordsArray.append(Word(wordDescribe: "BUZ DEVRİ", wordForbidden1: "ESKİ ÇAĞ", wordForbidden2: "SOĞUK ", wordForbidden3: "ERİMEK ", wordForbidden4: "KAR ", wordForbidden5: "ÇİZGİ FİLM"))
    wordsArray.append(Word(wordDescribe: "SALSA", wordForbidden1: "SOS ", wordForbidden2: "DANS ", wordForbidden3: "LATİN ", wordForbidden4: "İSPANYOL ", wordForbidden5: "PARTİ"))
    wordsArray.append(Word(wordDescribe: "BONCUK", wordForbidden1: "KOLYE ", wordForbidden2: "TAKI ", wordForbidden3: "RENKLİ ", wordForbidden4: "KÜÇÜK ", wordForbidden5: "YUVARLAK"))
    wordsArray.append(Word(wordDescribe: "TRAVESTİ", wordForbidden1: "ERKEK ", wordForbidden2: "KADIN ", wordForbidden3: "TRANSSEKSÜEL ", wordForbidden4: "KILIK ", wordForbidden5: "GİRMEK"))
    wordsArray.append(Word(wordDescribe: "DAKTİLO", wordForbidden1: "YAZMAK ", wordForbidden2: "HARF ", wordForbidden3: "KAĞIT ", wordForbidden4: "TUŞ ", wordForbidden5: "STİLO"))
    wordsArray.append(Word(wordDescribe: "TELSİZ", wordForbidden1: "TELEFON ", wordForbidden2: "KONUŞMAK ", wordForbidden3: "POLİS ", wordForbidden4: "İLETİŞİM ", wordForbidden5: "BASMAK"))
    wordsArray.append(Word(wordDescribe: "SANDAL", wordForbidden1: "MOTOR ", wordForbidden2: "DENİZ ", wordForbidden3: "KÜREK ", wordForbidden4: "SEFA ", wordForbidden5: "BALIKÇI"))
    wordsArray.append(Word(wordDescribe: "HAÇ", wordForbidden1: "HRİSTİYANLIK", wordForbidden2: "ÇAĞLA ŞİKEL", wordForbidden3: "ARTI İŞARETİ", wordForbidden4: "İSA ", wordForbidden5: "ÇARMIH"))
    wordsArray.append(Word(wordDescribe: "ASİT", wordForbidden1: "MAVİ ", wordForbidden2: "KIRMIZI ", wordForbidden3: "TURNUSOL ", wordForbidden4: "BAZ ", wordForbidden5: "MİDE"))
    wordsArray.append(Word(wordDescribe: "KUŞ BAKIŞI", wordForbidden1: "YÜKSEK ", wordForbidden2: "GENEL ", wordForbidden3: "HAYVAN ", wordForbidden4: "GÖRMEK ", wordForbidden5: "ALAN"))
    wordsArray.append(Word(wordDescribe: "HATIR", wordForbidden1: "GÖNÜL", wordForbidden2: "KALP ", wordForbidden3: "HAFIZA ", wordForbidden4: "ZİHİN", wordForbidden5: "KIRMAK"))
    wordsArray.append(Word(wordDescribe: "İMRENMEK", wordForbidden1: "KISKANMAK ", wordForbidden2: "GIPTA ETMEK", wordForbidden3: "ÖZENMEK ", wordForbidden4: "CANI ÇEKMEK", wordForbidden5: "İSTEMEK"))
    wordsArray.append(Word(wordDescribe: "DUMUR", wordForbidden1: "KÖRELMEK ", wordForbidden2: "APTALLAŞMAK ", wordForbidden3: "ŞOK OLMAK ", wordForbidden4: "ŞAŞIRMAK ", wordForbidden5: "ŞAŞKINA DÖNMEK"))
    wordsArray.append(Word(wordDescribe: "KAHIR", wordForbidden1: "MAHVETME ", wordForbidden2: "PERİŞAN ", wordForbidden3: "EZME ", wordForbidden4: "ÇEKMEK ", wordForbidden5: "ETMEK"))
    
    
    print("yeayyy")
    print(wordsArray.count)
    
}
/*
 tabooList.add(WordModel("KÖŞK","BAHÇE ","EV ","SÜSLÜ ","KASİR ","YAPI"))
 tabooList.add(WordModel("ALYANS","EVLİLİK ","YÜZÜK ","KARIKOCA ","PARMAK ","TAKMAK"))
 tabooList.add(WordModel("İKTİDAR","OTORİTE ","MUHALEFET ","YETKİ ","KUVVET ","PARTİ"))
 tabooList.add(WordModel("ÇIBAN","İRİN ","DERİ ","BİRİKMEK ","VÜCUT ","ÇIKMAK"))
 tabooList.add(WordModel("ARAP","SİYAH ","AFRİKA ","FELLAH ","SABUN ","BACI"))
 tabooList.add(WordModel("KALSİYUM","KEMİK ","SÜT ","PEYNİR ","YOĞURT ","DİŞ"))
 tabooList.add(WordModel("ÇAYIR","OTLAMAK ","İNEK ","YEŞİL ","ÇİMEN ","PİKNİK"))
 tabooList.add(WordModel("BALİNA","DENİZ","MEMELİ ","HAYVAN ","YUNUS","SU "))
 tabooList.add(WordModel("OLUMSUZ","NEGATİF ","ZARARLI ","UYGUN ","YAPICI ","YARARLI"))
 tabooList.add(WordModel("MİSYONER","DİN ","YAYMAK ","HRİSTİYAN ","ADAMAK ","DÜŞÜNCE"))
 tabooList.add(WordModel("SİNCAP","HAYVAN ","KEMİRMEK ","AĞAÇ ","FINDIK ","KOKARCA"))
 tabooList.add(WordModel("RAMAZAN BAYRAMI","ŞEKER ","KUTLAMAK ","KURBAN BAYRAMI ","TATİL ","DİNİ"))
 tabooList.add(WordModel("FARENJİT","HASTALIK ","BOĞAZ ","İLTİHAP ","TOZ ","SPREY"))
 tabooList.add(WordModel("ARSA","YER ","ALAN ","YAPI ","TARLA ","YAPMAK"))
 tabooList.add(WordModel("SAÇ","FÖN ","KUAFÖR BERBER ","KADIN ERKEK ","KESTİRMEK","BOYATMAK"))
 tabooList.add(WordModel("HARE","PARLAK ","ÇİZGİ ","DALGA ","SERT ","KUMAŞ"))
 tabooList.add(WordModel("BİLİNÇ","ŞUUR ","TANIMA ","BİLGİ ","GÖRÜŞ ","TEMEL"))
 tabooList.add(WordModel("KALABALIK","İNSAN ","ÇOK ","TOPLULUK ","KARGAŞA ","AŞIRI"))
 tabooList.add(WordModel("SOĞUK ALGINLIĞI","ÜŞÜTMEK ","HASTALIK ","ATEŞ ","NEZLE ","AKINTI"))
 tabooList.add(WordModel("MUTASYON","DEĞİŞİM ","EVRİM ","FARKLI ","GEÇİRMEK ","GEN"))
 tabooList.add(WordModel("NELSON MANDELA","SİYAHİ  ","AFRİKA  ","TUTUKLU  ","BAŞKAN ","LİDER"))
 tabooList.add(WordModel("UZAK DURMAK","YAKLAŞMAMAK ","İSTEMEMEK ","MESAFE ","KOYMAK ","YAKIN"))
 tabooList.add(WordModel("DENEY","KİMYA ","LABORATUVAR ","FARE ","BİLİM ","TÜP"))
 tabooList.add(WordModel("PÜSKÜL","SAÇAK ","İP ","SÜS ","FES ","MISIR"))
 tabooList.add(WordModel("EMBESİL","ZEKA GERİLİĞİ","APTAL ","AHMAK ","SALAK ","MORON"))
 tabooList.add(WordModel("BEDDUA","KÖTÜLÜK ","TUTMAK ","ALMAK ","ETMEK ","BELA"))
 tabooList.add(WordModel("DÖNME DOLAP","LUNAPARK ","YÜKSEK ","ÇOCUK ","EĞLENCE ","OTURMAK"))
 tabooList.add(WordModel("BABA","ERKEK","MAFYA","AİLE","ÇOCUK","ANNE"))
 tabooList.add(WordModel("GAZETE","BASIN","OKUMAK","MEDYA","İLAN","SAYFA"))
 tabooList.add(WordModel("KARATE","DÖVÜŞ SANATLARI","YUMRUK","TEKME","KİD","KAVGA"))
 tabooList.add(WordModel("CAMİ","İMAM","NAMAZ","MÜSLÜMAN","CEMAAT","İBADET"))
 tabooList.add(WordModel("TERLİK","AYAKKABI","HAFİF","ANNE","GİYMEK","EV"))
 tabooList.add(WordModel("ÖRMEK","ŞİŞ","YÜN","KAZAK","DANTEL","ATKI"))
 tabooList.add(WordModel("KLİMA","KALORİFER","SOĞUK","DUVAR","YAZ","SICAK"))
 tabooList.add(WordModel("ÜNİVERSİTE","OKUL","ÖSS","FAKÜLTE","EĞİTİM","ÖĞRENCİ"))
 tabooList.add(WordModel("KRAVAT","GÖMLEK","TAKIM ELBİSE","MEDENİYET YULARI","BOYUN","YAKA"))
 tabooList.add(WordModel("FASULYE","PİLAV","KURU","GAZ","SIRIK","YEMEK"))
 tabooList.add(WordModel("DEDE KORKUT","EFSANE","ERGENEKON","DESTAN","HİKAYE","ESKİ"))
 tabooList.add(WordModel("TAHAMÜL ETMEK","SABIR","DAYANMAK","ARTIK","SINIR","KATLANMAK"))
 tabooList.add(WordModel("SALDIRGAN","AGRESİF","TEHLİKE","KAVGA","ZARAR","DÜŞMAN"))
 tabooList.add(WordModel("ŞİKAYET","HOŞNUTSUZ","MEMNUNİYET","YAKINMAK","TÜKETİCİ","DERT"))
 tabooList.add(WordModel("MEŞALE","ATEŞ","IŞIK","AYDINLIK","YAKMAK","OLİMPİYAT"))
 tabooList.add(WordModel("UYUZ","BULAŞICI","GICIK ETMEK","KÖPEK","HASTALIK","KAŞINMAK"))
 tabooList.add(WordModel("BEZE","HAMUR","YAĞ","PASTA","PİŞKİNLİK","PAZ"))
 tabooList.add(WordModel("TOSBAĞA","VOSVOS","ARABA","KABUK","KAPLUMBAĞA","ESKİ"))
 tabooList.add(WordModel("BÖCEK","ZEHİR","SİNEK","HAŞERE","HAYVAN","YARATIK"))
 tabooList.add(WordModel("YATAKHANE","YATILI","YURT","KIŞLA","OKUL","YATMAK"))
 tabooList.add(WordModel("UZLAŞMAK","İŞBİRLİĞİ","MUTABAKAT","UYUŞMA","ANLAŞMA","İTTİFAK"))
 tabooList.add(WordModel("MAKİNİST","METRO","SİNEMA","FİLM","TREN","KULLANMAK"))
 tabooList.add(WordModel("AYDINLATMAK","GÖRÜNMEK","IŞIK","BİLGİLENDİRMEK","KARANLIK","GİDERMEK"))
 tabooList.add(WordModel("ÇALMAK","POLİS","HIRSIZ","ARANMAK","İZİN","EV"))
 tabooList.add(WordModel("ÇATLAK","ARALIK","AYRILMAK","DELİ","ARA","YARILMAK"))
 tabooList.add(WordModel("ALİM","BİLGE","AKILLI","ZEKİ","HOCA","BİLGİN"))
 tabooList.add(WordModel("LEKE","İZ","ÇAMAŞIR","RENK","ÇIKARTMAK","KİR"))
 tabooList.add(WordModel("BİLMECE","TEKERLEME","SORMAK","OYUN","BULMACA","GİZLİ"))
 tabooList.add(WordModel("LAPTOP","ELDE","BİLGİSAYAR","ÇANTA","MASAÜSTÜ","KASASIZ"))
 tabooList.add(WordModel("EMEKLEMEK","BEBEK","SÜRÜNMEK","YÜRÜMEZ","DİZ","YER"))
 tabooList.add(WordModel("TUĞLA","BLOK","DUVAR","İNŞAAT","MALZEME","YAPI"))
 tabooList.add(WordModel("SAĞLAM","SAĞLIKLI","SIHHATLİ","BOZULMAZ","DAYANIKLI","YIKILMAZ"))
 tabooList.add(WordModel("BİBERON","BEBEK","SÜT","ANNE","EMZİK","YEMEK"))
 tabooList.add(WordModel("KAZMA","TOPRAK","İŞLEMEK","DÜZELTMEK","ÇAPA","ARAÇ"))
 tabooList.add(WordModel("TEKRAR","BİR DAHA","GENE","YENİDEN","YAPMAK","YİNE"))
 tabooList.add(WordModel("AĞZINDAN KAÇIRMAK","AÇIĞA VURMAK","ORTAYA ÇIKARTMAK","POT KIRMAK","GERÇEK","DOĞRU"))
 tabooList.add(WordModel("MAKİNE","CİHAZ","ÇALIŞMAK","BOZULMAK","MÜHENDİS","ALET"))
 tabooList.add(WordModel("METAL","AMETAL","İLETKEN","MADEN","DEMİR","KİMYA"))
 tabooList.add(WordModel("YABANCI","DİL","LİSAN","AVRUPA","TURİST","FARKLI"))
 tabooList.add(WordModel("GÖÇ","DEĞİŞTİRMEK","KUŞ","GİTMEK","TAŞINMAK","HAYVAN"))
 tabooList.add(WordModel("KÜSMEK ","DARILMAK ","KIZMAK ","KONUŞMAK ","TARTIŞMAK ","KAVGA"))
 tabooList.add(WordModel("AVİZE","LAMBA","KRİSTAL","TAVAN","IŞIK","AYDINLIK"))
 tabooList.add(WordModel("KOORDİNAT","YER","ENLEM","BOYLAM","BELİRTMEK","VERMEK"))
 tabooList.add(WordModel("TERİM","KELİME","ANLAM","FATİH","SANAT","KAVRAM"))
 tabooList.add(WordModel("SOYUT","DUYU","ALGILAMAK","GÖRÜLMEYEN","İSİM","SOMUT"))
 tabooList.add(WordModel("BASKÜL","TARTI","KİLO","AĞIR","ÖLÇÜ","HAFİF"))
 tabooList.add(WordModel("HALÜSİNASYON","HAYAL","GERÇEK","GÖRMEK","İLLÜZYON","SERAP"))
 tabooList.add(WordModel("ADEM ELMASI","ERKEK","GIRTLAK","ÇIKINTI","BOĞAZ","HAVVA"))
 tabooList.add(WordModel("SATRANÇ","ŞAH-MAT","KALE","VEZİR","PİYON","FİL"))
 tabooList.add(WordModel("PARAŞÜT","UÇAK","ATLAMAK","UÇMAK","BALON","HAVA"))
 tabooList.add(WordModel("DOST","GÜVEN","SAMİMİ","DÜRÜST","ARKADAŞ","AHLAKLI"))
 tabooList.add(WordModel("KEDİ","PATİ","FARE","TÜY","KUYRUK","HAYVAN"))
 tabooList.add(WordModel("BONKÖR","ELİ AÇIK","CÖMERT","PARA","GÖNLÜ ZENGİN","HARCAMAK"))
 tabooList.add(WordModel("MESAİ","SAAT","İŞ","FAZLA","AKŞAM","KALMAK"))
 tabooList.add(WordModel("YELPAZE","SICAK","RÜZGAR","YAZ","KADIN","SALLAMAK"))
 tabooList.add(WordModel("İŞTAH","ACIKMAK","KESİLMEK","AÇMAK","LEZZET","YEMEK"))
 tabooList.add(WordModel("HALAY","DÜĞÜN","ÇEKMEK","OYNAMAK","MENDİL","MAHMUT TUNCER"))
 tabooList.add(WordModel("PLAKET","ÖDÜL","TÖREN","BAŞARI","VERMEK","TEŞEKKÜR"))
 tabooList.add(WordModel("STAJ","ÖĞRENCİ","ÇALIŞMAK","ÜNİVERSİTE","TECRÜBE","İŞ"))
 tabooList.add(WordModel("TECRÜBE","İŞ","KAZANMAK","ÇALIŞMAK","DENEYİM","YIL"))
 tabooList.add(WordModel("MACUN","CAM","PENCERE","TUTMAK","DİŞ","MESİR"))
 tabooList.add(WordModel("MIZIKÇI","ÇOCUK","KÜSMEK","DARILMAK","BOZMAK","OYUN"))
 tabooList.add(WordModel("ÇAVDAR","ARPA","TAHIL","BUĞDAY","KEPEK","EKMEK"))
 tabooList.add(WordModel("ESKİMO","KUTUP","BUZUL","KAR","SOĞUK","BALIK"))
 tabooList.add(WordModel("BUKALEMUN","HAYVAN","RENK","KERTENKELE","DEĞİŞMEK","SÜRÜNGEN"))
 tabooList.add(WordModel("CEPHE","SAVAŞ","ORDU","ASKER","SALDIRMAK","BARIŞ"))
 tabooList.add(WordModel("PARAGRAF","SINAV","SORU","ANA DÜŞÜNCE","YARDIMCI DÜŞÜNCE","METİN"))
 tabooList.add(WordModel("ÜÇ NOKTA","NOKTALAMA","SON","TAMAMLANMAMIŞ","İSTENMEYEN","CÜMLE"))
 tabooList.add(WordModel("KORNİŞ ","TAVAN ","PERDE ","ASMAK ","PENCERE ","CAM"))
 tabooList.add(WordModel("NİHALE ","ALTLIK ","TENCERE ","ÇAYDANLIK ","SICAK ","TEZGÂH"))
 tabooList.add(WordModel("DUY ","TAVAN ","LAMBA ","IŞIK ","İŞİTMEK ","ANAHTAR"))
 tabooList.add(WordModel("ARMAĞAN ","HEDİYE ","VERMEK ","ALMAK ","DOĞUM GÜNÜ ","SEVİNDİRMEK"))
 tabooList.add(WordModel("KUMBARA ","PARA ","BİRİKTİRMEK ","YATIRIM ","BANKA ","SAKLAMAK"))
 tabooList.add(WordModel("ANTİKA ","MÜZAYEDE ","ZENGİN ","ESKİ ","TABLO ","TARİHİ"))
 tabooList.add(WordModel("SAĞDIÇ","DAMAT","DÜĞÜN","GELİN","GÜVEY","SIRTINA VURMAK"))
 tabooList.add(WordModel("KABZIMAL","MEYVE","SEBZE","HAL","SATMAK","ARACI"))
 tabooList.add(WordModel("MANGALA","OYUN","OSMANLI","KUYU","TAŞ","HAZİNE"))
 tabooList.add(WordModel("BALMUMU","MUM","ERİMEK","HEYKEL","MÜZE","BAL"))
 tabooList.add(WordModel("FERMUAR","PANTOLON","MONT","GİYSİ","KIYAFET","KOT"))
 tabooList.add(WordModel("KELEBEK","RENKLİ","UÇMAK","TIRTIL","KOZA","HAYVAN"))
 tabooList.add(WordModel("MALA","İNŞAAT","DUVAR","USTA","SIVA","ÇİMENTO"))
 tabooList.add(WordModel("TİYATRO","OYUNCU","SAHNE","PERDE","OYUN","SUFLÖR"))
 tabooList.add(WordModel("BAĞLAMA","TÜRKÜ","MÜZİK","SAZ","TEL","AKORT"))
 tabooList.add(WordModel("DERGİ","GAZETE","MECMUA","MAKALE","YAZI","KAPAK"))
 tabooList.add(WordModel("KAPAN","AV","KURT","HAYVAN","TUZAK","FARE"))
 tabooList.add(WordModel("EMPATİ","KENDİNİ","BAŞKASI","YERİNE","KOYMA","DÜŞÜNME"))
 tabooList.add(WordModel("ANAHTAR","KİLİT","METAL","KASA","KAPI","ÇİLİNGİR"))
 tabooList.add(WordModel("HOŞGÖRÜ","MEVLANA","ANLAYIŞ","EMPATİ","NE OLURSAN","GEL"))
 tabooList.add(WordModel("ULEMA","BİLGİN","OSMANLI","DİN","ALİM","HOCA"))
 tabooList.add(WordModel("HEYBETLİ","YÜCE","DAĞ","BÜYÜK","YÜKSEK","İRİ"))
 tabooList.add(WordModel("ÇIRA","ATEŞ","YAKMAK","ODUN","TAHTA","ÇAY"))
 tabooList.add(WordModel("FİDAN","AĞAÇ","BÜYÜMEK","KÜÇÜK","ORMAN","DİKMEK"))
 tabooList.add(WordModel("PRATİK","KOLAY","ZEKÂ","ÇABUK","HIZLI","ÇÖZÜM"))
 tabooList.add(WordModel("KIVILCIM","ATEŞ","KİBRİT","ÇAKMAK","TAŞ","SÜRTMEK"))
 tabooList.add(WordModel("MİSKİN","TEMBEL","UYUŞUK","YAVAŞ","AĞIR","KEDİ"))
 tabooList.add(WordModel("KÖHNE","ESKİ","TARİHİ","YIKILMAK","BİNA","HARABE"))
 tabooList.add(WordModel("AKROSTİŞ","ŞİİR","MISRA","İSİM","İLK","KITA"))
 tabooList.add(WordModel("YAYIK","AYRAN","SU","YOĞURT","ÇALKALAMAK","SÜT"))
 tabooList.add(WordModel("BAMBU","SAZLIK","MOBİLYA","AĞAÇ","MASA","SANDALYE"))
 tabooList.add(WordModel("YABANİ","VAHŞİ","İLKEL","HAYAT","ORMAN","HAYVAN"))
 tabooList.add(WordModel("GÖÇMEN","MÜLTECİ","VİZE","SOĞUK","KUŞ","SICAK"))
 tabooList.add(WordModel("ÇUVAL","TORBA","DOLDURMAK","YEM","UN","KOYMAK"))
 tabooList.add(WordModel("TALİMAT","EMİR","VERMEK","FATURA","BANKA","OTOMATİK ÖDEME"))
 tabooList.add(WordModel("SİFTAH","İLK","GÜN","SATMAK","MAL","ALIŞVERİŞ"))
 tabooList.add(WordModel("FLAMA","BAYRAK","ÜÇGEN","OKUL","İZCİ","TÖREN"))
 tabooList.add(WordModel("MÜSVEDDE","KARALAMA","NOT ALMAK","YAZMAK","KÂĞIT","TEMİZ"))
 tabooList.add(WordModel("AJANDA","DEFTER","İŞ","YAZMAK","GÜN","TOPLANTI"))
 tabooList.add(WordModel("İHALE","BELEDİYE","GİRMEK","AÇMAK","YOLSUZLUK","KAZANMAK"))
 tabooList.add(WordModel("UYANIK","AKILLI","ZEKİ","AÇIKGÖZ","KURNAZ","SAF"))
 tabooList.add(WordModel("PASAKLI","TEMİZ","TİTİZ","KİRLİ","DÜZENLİ","KARIŞIK"))
 tabooList.add(WordModel("HİLE","ALDATMAK","KANDIRMAK","OYUN","YAPMAK","KUMAR"))
 tabooList.add(WordModel("FİRAR","KAÇAK","HAPİS","ASKER","MAHKÛM","ETMEK"))
 tabooList.add(WordModel("FULAR","EŞARP","BAĞLAMAK","BAŞ","BOYUN","KADIN"))
 tabooList.add(WordModel("KAOS","KARIŞIKLIK","ORTAM","KARGAŞA","DÜZEN","YARATMAK"))
 tabooList.add(WordModel("SIRIK","UZUN","ATLAMAK","BOY","ATLETİZM","FASULYE"))
 tabooList.add(WordModel("ARIZA","BOZUK","TAMİR","ÇALIŞMAK","TELEFON","ELEKTRİK"))
 tabooList.add(WordModel("SUİSTİMAL","İYİ","NİYET","KULLANMAK","FAYDALANMAK","KÖTÜ"))
 tabooList.add(WordModel("SISKA","ZAYIF","İNCE","ÇELİMSİZ","ŞİŞMAN","HASTA"))
 tabooList.add(WordModel("ESİR","MAHKÛM","SAVAŞ","DÜŞMEK","TUTSAK","KAMP"))
 tabooList.add(WordModel("NADİR","ZOR","AZ","BULMAK","SIK","ÇOK"))
 tabooList.add(WordModel("BUĞU","BUHAR","CAM","SU","SICAK","ARABA"))
 tabooList.add(WordModel("PATİKA","KEÇİ YOLU","DAĞ","ORMAN","KESTİRME","YÜRÜMEK"))
 tabooList.add(WordModel("VERESİYE","PEŞİN","BORÇ","SATIN ALMAK","ÖDEMEK","DEFTER"))
 tabooList.add(WordModel("ABLUKA","ETRAF","KUŞATMA","SAVAŞ","ÇEVİRMEK","DÜŞMAN"))
 tabooList.add(WordModel("UCUZLUK","İNDİRİM","PAHALI","YÜZDE","FİYAT","VİTRİN"))
 tabooList.add(WordModel("PERFORMANS","DEĞERLENDİRME","BAŞARI","DERS","ÖDEV","YÜKSEK"))
 tabooList.add(WordModel("PARANOYA","ŞÜPHE","AKIL","RUH","HASTALIK","DELİ"))
 tabooList.add(WordModel("GÜZERGÂH","YOL","ARABA","ROTA","SERVİS","TAKİP ETMEK"))
 tabooList.add(WordModel("FESHETMEK","ANTLAŞMA","SÖZLEŞME","İPTAL","GEÇERSİZ","BOZMAK"))
 tabooList.add(WordModel("ZEYBEK","ATATÜRK","OYUN","EGE","EFE","SARI"))
 tabooList.add(WordModel("YADIRGAMAK","GARİP","TUHAF","KABULLENMEK","ŞAŞIRMAK","DAVRANIŞ"))
 tabooList.add(WordModel("MONOTON","AYNI","SIKICI","SIRADAN","BENZER","RUTİN"))
 tabooList.add(WordModel("DİYAR","MEMLEKET","VATAN","DOLAŞMAK","GEZMEK","ÂŞIK VEYSEL"))
 tabooList.add(WordModel("DOZ","MİKTAR","İLAÇ","DOKTOR","REÇETE","AŞIRI"))
 tabooList.add(WordModel("PORSİYON","YEMEK","TABAK","LOKANTA","YARIM","RESTORAN"))
 tabooList.add(WordModel("KABİN","GİYİNMEK","DUŞ","DENEMEK","MAĞAZA","KIYAFET"))
 tabooList.add(WordModel("SERVET","KAZANMAK","ZENGİNLİK","MAL","MÜLK","PARA"))
 tabooList.add(WordModel("TEDARİK","BULMAK","SAĞLAMAK","MALZEME","ETMEK","HAZIRLIK"))
 tabooList.add(WordModel("TABURE","OTURMAK","SANDALYE","KOLTUK","YEMEKHANE","SIRT"))
 tabooList.add(WordModel("EREZYON","TOPRAK","KAYMA","AĞAÇ","HEYELAN","TEMA"))
 tabooList.add(WordModel("ÇAMAŞIR","KİRLİ","YIKAMAK","MAKİNE","DETERJAN","GİYMEK"))
 tabooList.add(WordModel("NUMUNE","ÖRNEK","VERMEK","TAHLİL","YEMEK","KÜÇÜK"))
 tabooList.add(WordModel("VİRAN","ESKİ","YIKIK","HARAP","EV","KÖHNE"))
 tabooList.add(WordModel("KASVET","SIKINTI","GAM","KARANLIK","AYDINLIK","NEŞELİ"))
 tabooList.add(WordModel("MİÇO","TAYFA","GEMİ","KAPTAN","DENİZ","YARDIMCI"))
 tabooList.add(WordModel("HAMAK","YATMAK","AĞAÇ","SALLANMAK","KURMAK","PİKNİK"))
 tabooList.add(WordModel("GADDAR","ACIMASIZ","SERT","KATI","MERHAMET","İNSAF"))
 tabooList.add(WordModel("ÇADIR","KAMP","UYKU TULUMU","TATİL","KURMAK","DOĞA"))
 tabooList.add(WordModel("NADAS","TARLA","EKMEK","BIRAKMAK","DİNLENDİRMEK","ÇİFTÇİ"))
 tabooList.add(WordModel("HASIR","SEPET","ŞAPKA","PLAJ","DENİZ","SERMEK"))
 tabooList.add(WordModel("KONVOY","ARABA","GİTMEK","DİZİLMEK","ARKA","DÜĞÜN"))
 tabooList.add(WordModel("TAKUNYA","TAHTA","TERLİK","AYAKKABI","GİYMEK","HAMAM"))
 tabooList.add(WordModel("AKSİ","SİNİRLİ","TERS","ZIT","ASABİ","HUYSUZ"))
 tabooList.add(WordModel("VEZNE","BANKA","PARA","ÖDEME","ALMAK","MUHASEBE"))
 tabooList.add(WordModel("OLUK","AKMAK","SU","YAĞMUR","SAÇAK","BORU"))
 tabooList.add(WordModel("YAMAÇ","UÇURUM","YÜKSEK","DAĞ","DİK","PARAŞÜT"))
 tabooList.add(WordModel("PİL","KALEM","İNCE","KUMANDA","EL FENERİ","FEN"))
 tabooList.add(WordModel("ZİRAAT","TARIM","ÇİFTÇİ","TOPRAK","HAYVAN","BANKA"))
 tabooList.add(WordModel("PROSPEKTÜS","İLAÇ","ECZANE","OKUMAK","İÇİNDEKİLER","KULLANMAK"))



 
 */
